[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.x"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_USE_NODE_BAKERY = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "next"
  targetPort = 3000
  command = "npm run dev"
